import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { Layout } from '../components/Layout'
import { SessionProvider } from 'next-auth/react'
import { EmotionCache } from '@emotion/react';

interface MyAppProps extends AppProps {
  emotionCache?: EmotionCache;
}

import { CacheProvider } from "@emotion/react";
import createCache from '@emotion/cache';
import { Head } from 'next/document';
import Link from 'next/link';
import favicon from "../assets/favicon.ico"

function createEmotionCache() {
    return createCache({ key: 'css', prepend: true });
}

const clientSideEmotionCache = createEmotionCache();

export default function App({ Component, pageProps, emotionCache = clientSideEmotionCache }: MyAppProps) {

  return (
    <CacheProvider value={emotionCache}>
      <SessionProvider session={pageProps.session}>
        <Layout>
          <Head>
            <title>BZ Commendations</title>
            <Link href={favicon.src}></Link>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
          </Head>
          <Component {...pageProps} />
        </Layout>
      </SessionProvider>
    </CacheProvider>
  )
}
