import Head from 'next/head'
import { CommendationForm } from "../components/CommendationForm"
import { readAllMembers } from '../lib/api/commendations';
import { Member } from '@prisma/client';
import { GetServerSideProps } from 'next';


export const getServerSideProps: GetServerSideProps = async (context) => {
  const members = await readAllMembers();
  return {
    props: { members }
  }
}

export default function Home({ members }: { members: Array<Member> }) {
  return (
    <>
      <Head>
        <title>BZ Commendations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CommendationForm members={members} />
      </main>
    </>
  )
}
