import Head from 'next/head'
import { Header } from "../components/Header"
import { CommendationForm } from "../components/CommendationForm"

export default function Home() {
  return (
    <>
      <Head>
        <title>BZ Commendations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header></Header>
        <CommendationForm></CommendationForm>
      </main>
    </>
  )
}
