import { AppProps } from "next/app";
import Head from "next/head";
import { CommendationCard } from "../components/CommendationCard";
import { Layout } from "../components/Layout";
import { readUserCommendations } from "../lib/api/commendations";

export async function getServerSideProps() {
  const comms = await readUserCommendations();
  return {
    props: { comms }
  }
}

export default function MyCommendations({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>BZ Commendations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CommendationCard />
      </main>
    </>
  )
}

// TO DO:
// 2. map all commendations in return statement to paper component (MUI)
// 3. inside paper component, implement 3 typographies & an avatar component (within in a BOX component)
// 3a. sender (commendation.from.name)
// 3b. date (commendation.createdAt.toLocateDataString{})
// 3c. message (commendation.message)
// 4. update typographies to match theme (3a, fontWeight="bold"; 3b, variant="caption")
// 5. center paper component and implement typgraphy header: YOUR COMMENDATIONS (fontFamily="fantasy")

// QUESTION(S):
// should the function be named "me" since that is what the MyCommendations button is linked to: "/me"??