import { GetServerSidePropsContext, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import CommendationForm from "../components/CommendationForm";
import { getTeams } from "../lib/api/teams";

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const teams = await getTeams();

  return {
    props: { teams }
  }
}

export default function TeamCommendation({ teams }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>BZ Commendations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CommendationForm recipients={teams} team />
      </main>
    </>
  )
}